# Generated by Django 5.2 on 2025-09-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
