# Generated by Django 5.2 on 2025-09-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_time',
        ),
    ]
