# Generated by Django 5.2 on 2025-11-16 05:29

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=cart.models.generate_order_number, max_length=20, unique=True),
        ),
    ]
